<x-layouts.app title="Subscribers">
    <div class="mb-6"><p class="text-sm text-slate-500">Unique MSISDNs with valid Combo purchases. Subscription and agent work statuses are independent.</p></div>
    @if(session('success')) <div class="mb-5 rounded-lg border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm text-emerald-800">{{ session('success') }}</div> @endif
    <form class="mb-5 grid gap-3 rounded-lg border border-slate-200 bg-white p-4 lg:grid-cols-4" method="GET">
        <input name="q" value="{{ request('q') }}" placeholder="Search MSISDN" class="rounded-md border border-slate-300 p-2 text-sm">
        <select name="subscription_status" class="rounded-md border border-slate-300 p-2 text-sm"><option value="">All subscription statuses</option><option value="Active" @selected(request('subscription_status') === 'Active')>Active</option><option value="Expired" @selected(request('subscription_status') === 'Expired')>Expired</option></select>
        <select name="agent_status" class="rounded-md border border-slate-300 p-2 text-sm"><option value="">All agent statuses</option><option value="PENDING" @selected(request('agent_status') === 'PENDING')>Pending</option><option value="COMPLETED" @selected(request('agent_status') === 'COMPLETED')>Completed</option></select>
        <button class="rounded-md bg-teal-700 px-4 py-2 text-sm font-medium text-white">Filter</button>
    </form>
    <section class="overflow-hidden rounded-lg border border-slate-200 bg-white"><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase text-slate-500"><tr>@foreach(['ID','MSISDN','Package','Purchase Date','Expiry Date','Price','Subscription Status','Agent Status','Action','Done By'] as $h)<th class="whitespace-nowrap px-4 py-3">{{ $h }}</th>@endforeach</tr></thead><tbody>@forelse($subscribers as $s)<tr class="border-t"><td class="px-4 py-4">#{{ $s->current->id }}</td><td class="px-4 py-4">{{ $s->msisdn }}</td><td class="px-4 py-4">{{ $s->current->package }}</td><td class="whitespace-nowrap px-4 py-4">{{ \Carbon\Carbon::parse($s->current->purchase_date)->format('d M Y, H:i') }}</td><td class="whitespace-nowrap px-4 py-4">{{ \Carbon\Carbon::parse($s->current->expiry_date)->format('d M Y, H:i') }}</td><td class="px-4 py-4">{{ number_format($s->current->price, 2) }}</td><td class="px-4 py-4"><x-status :value="$s->current->status" /></td><td class="px-4 py-4"><x-status :value="$s->agent_status" /></td><td class="px-4 py-4">@if($s->agent_status === 'PENDING')<form method="POST" action="{{ route('subscribers.complete', $s->current->id) }}">@csrf<button class="rounded bg-teal-700 px-2.5 py-1 text-xs font-medium text-white">Complete</button></form>@else<span class="text-xs font-medium text-emerald-700">Completed</span>@endif <a class="ml-2 text-xs text-teal-700" href="{{ route('subscribers.show', $s->msisdn) }}">View</a></td><td class="px-4 py-4">{{ optional(optional($s->action)->doneBy)->displayName() ?: '—' }}</td></tr>@empty<tr><td colspan="10" class="p-8 text-center text-slate-500">No valid subscribers match the selected filters.</td></tr>@endforelse</tbody></table></div><div class="border-t px-4 py-3">{{ $subscribers->appends(request()->query())->links() }}</div></section>
</x-layouts.app>
